spring.application.name=demo

loopCount=10
testerName=Spring Tester

# CoffeeMaker 클래스에서는 debug 레벨 이상의 모든 로그를 출력하고,
# 그 밖의 클래스에서는 info 레벨 이상의 로그만 출력
logging.level.root=info
logging.level.com.example.demo.CoffeeMaker=debug

# 출력할 로그 파일 경로
logging.file.name=./log/app.log

# 로그 백업 시 파일 이름의 패턴(%d는 백업 날짜, %i는 동일한 날짜에 여러 개의 백업 파일이
# 생성될 경우 1부터 시작하는 일련번호, 확장자가 gz라면 gzip으로 백업 파일 압축)
logging.logback.rollingpolicy.file-name-pattern=./log/app.backup.%d{yyyy-MM-dd}.%i.gz

# 백업 파일의 보관 일수
logging.logback.rollingpolicy.max-history=7

# 로그 파일의 크기가 10KB를 넘으면 백업
logging.logback.rollingpolicy.max-file-size=10KB

# 백업 전체 크키가 1GB를 넘으면 오래된 백업부터 삭제
logging.logback.rollingpolicy.total-size-cap=1GB