spring.application.name=demo

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:bbs
spring.h2.console.enabled=true

# 애플리케이션 시작 지점에 sql.init 설정 적용
# resources하위의 schema.sql과 data.sql을 자동으로 실행하도록 설정
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8

# JPA Hibernate가 DDL 생성 기능을 사용하지 않도록 설정
# JPA 스키마 자동 생성 X -> SQL로 직접 스키마 관리
spring.jpa.hibernate.ddl-auto=none