spring.application.name=jpa

# 연결할 데이터베이스 설정
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

# 애플리케이션 실행 시 스키마를 새롭게 생성하도록 설정
spring.jpa.hibernate.ddl-auto=create

# JPA SQL 로그를 활성화하여 실행되는 SQL 쿼리를 콘솔에 출력
spring.jpa.show-sql=true

# JPA SQL 로그 출력 시 줄바꿈을 추가해 가독성을 높임
spring.jpa.properties.hibernate.format_sql=true

# JPA SQL 로그 출력 시 SQL 키워드에 색상 또는 스타일을 포함해 더 읽기 쉽게 출력
spring.jpa.properties.hibernate.highlight_sql=true

# JPA SQL 로그 출력 시 매핑된 객체 정보 등을 주석 형태로 출력
spring.jpa.properties.hibernate.use_sql_comments=true

# JPA SQL 로그 출력 시 바인딩된 매개변수 값도 함께 출력
logging.level.org.hibernate.orm.jdbc.bind=trace