spring.application.name=demo

# 스프링 시큐리티 동작 확인용 사용자 계정
spring.security.user.name=admin
spring.security.user.password=qwe123
spring.security.user.roles=USER,ADMIN

# 데이터베이스 설정
# 고정 URL, 콘솔 활성화
spring.datasource.url=jdbc:h2:mem:mydb
spring.h2.console.enabled=true

# SQL 스크립트 초기화 설정(예: 시작 시점에 사용자 자동 INSERT)
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8

# 스크립트 자동 생성 설정
spring.jpa.hibernate.ddl-auto=none